apiVersion: v1
kind: Service
metadata:
  labels:
    app: gw-dep
  name: gw-svc
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
    nodePort: 32002
  selector:
    app: gw-dep
  type: NodePort
