apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-dep
  name: auth-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32001
  selector:
    app: auth-dep
  type: NodePort
